// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as Counters$ReactHooksTemplate from "./Counters.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Counters$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "root");

export {
  
}
/*  Not a pure module */
