// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Styles$ReactHooksTemplate from "./Styles.bs.js";

function Layout(Props) {
  var children = Props.children;
  var match = Props.username;
  var username = match !== undefined ? match : "Default User";
  return React.createElement("div", {
              className: Styles$ReactHooksTemplate.wrapperStyles
            }, React.createElement("nav", undefined, React.createElement("li", undefined, username)), React.createElement("div", {
                  className: "content"
                }, children), React.createElement("footer", undefined, React.createElement("h3", undefined, "Created for Egghead.io - 2019")));
}

var make = Layout;

export {
  make ,
  
}
/* react Not a pure module */
