// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var Counters$ReactHooksTemplate = require("./Counters.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Counters$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "root");

/*  Not a pure module */
