// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Component2(Props) {
  var greeting = Props.greeting;
  var match = React.useReducer((function (state, action) {
          if (typeof action === "number") {
            switch (action) {
              case /* Click */0 :
                  return /* record */[
                          /* count */state[/* count */0] + 1 | 0,
                          /* show */state[/* show */1],
                          /* incrementValue */state[/* incrementValue */2]
                        ];
              case /* IncrementCount */1 :
                  state[/* incrementValue */2][0] = state[/* incrementValue */2][0] + 1 | 0;
                  return /* record */[
                          /* count */state[/* count */0],
                          /* show */state[/* show */1],
                          /* incrementValue */state[/* incrementValue */2]
                        ];
              case /* Toggle */2 :
                  return /* record */[
                          /* count */state[/* count */0],
                          /* show */!state[/* show */1],
                          /* incrementValue */state[/* incrementValue */2]
                        ];
              
            }
          } else {
            return /* record */[
                    /* count */state[/* count */0] + action[0] | 0,
                    /* show */state[/* show */1],
                    /* incrementValue */state[/* incrementValue */2]
                  ];
          }
        }), /* record */[
        /* count */0,
        /* show */true,
        /* incrementValue : record */[/* contents */0]
      ]);
  var dispatch = match[1];
  var state = match[0];
  var message = "You've clicked this " + (String(state[/* count */0]) + " times(s)");
  var match$1 = state[/* show */1];
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Click */0);
                    })
                }, message), React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* AddMany */[5]);
                    })
                }, "Add Many to Count"), React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Toggle */2);
                    })
                }, "Toggle greeting"), match$1 ? greeting : null);
}

var make = Component2;

exports.make = make;
/* react Not a pure module */
