// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Layout$ReactHooksTemplate = require("./Layout.bs.js");

function Counters(Props) {
  var match = Props.greeting;
  var greeting = match !== undefined ? match : "Default Greeting";
  var match$1 = React.useReducer((function (state, action) {
          switch (action) {
            case /* Click */0 :
                return /* record */[
                        /* count */state[/* count */0] + 1 | 0,
                        /* incrementValue */state[/* incrementValue */1]
                      ];
            case /* UpdateIncrementValue */1 :
                console.log(state[/* incrementValue */1][0]);
                state[/* incrementValue */1][0] = state[/* incrementValue */1][0] + 1 | 0;
                return /* record */[
                        /* count */state[/* count */0],
                        /* incrementValue */state[/* incrementValue */1]
                      ];
            case /* AddMany */2 :
                return /* record */[
                        /* count */state[/* count */0] + state[/* incrementValue */1][0] | 0,
                        /* incrementValue : record */[/* contents */0]
                      ];
            
          }
        }), /* record */[
        /* count */0,
        /* incrementValue : record */[/* contents */0]
      ]);
  var dispatch = match$1[1];
  var state = match$1[0];
  var message = "You've clicked this " + (String(state[/* count */0]) + " times(s)");
  return React.createElement(Layout$ReactHooksTemplate.make, {
              children: null,
              username: "tgrecojs"
            }, React.createElement("h2", undefined, greeting), React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Click */0);
                    })
                }, message), React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (_event) {
                          return Curry._1(dispatch, /* UpdateIncrementValue */1);
                        })
                    }, "Increase Increment Value::" + String(state[/* incrementValue */1][0])), React.createElement("button", {
                      onClick: (function (_event) {
                          return Curry._1(dispatch, /* AddMany */2);
                        })
                    }, "Add Increment Value to Count")));
}

var make = Counters;

exports.make = make;
/* react Not a pure module */
