// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Layout(Props) {
  var username = Props.username;
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, React.createElement("nav", undefined, React.createElement("li", undefined, "Signed in as:" + username)), React.createElement("div", {
                  className: "content"
                }, children), React.createElement("footer", undefined, React.createElement("h4", undefined, "Footer text")));
}

var make = Layout;

exports.make = make;
/* react Not a pure module */
