// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

Css.$$global(".content", /* :: */[
      Css.flex(/* `num */[
            5496390,
            1.0
          ]),
      /* [] */0
    ]);

var wrapperStyles = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.minHeight(Css.vh(100)),
          /* [] */0
        ]
      ]
    ]);

var button = Css.style(/* :: */[
      Css.width(Css.px(300)),
      /* :: */[
        Css.fontSize(Css.px(18)),
        /* :: */[
          Css.color(Css.hex("FFF")),
          /* :: */[
            Css.backgroundColor(Css.hex("042E89")),
            /* [] */0
          ]
        ]
      ]
    ]);

var Styles = {
  wrapperStyles: wrapperStyles,
  button: button
};

var AppDesign = {
  wrapperStyles: wrapperStyles,
  button: button
};

exports.Styles = Styles;
exports.AppDesign = AppDesign;
/*  Not a pure module */
